name: CMake Build Matrix

# Controls when the action will run. Triggers the workflow on push
on: 
  push:
    branches:
      - gha-build

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }} # будет запускаться по очереди на всех типах машин
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            artifact: "windows_msvc.7z",
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            archiver: "7z a",
            generators: "Visual Studio 16 2019",
            python_version: 2.7
          }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true


      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      
      - uses: actions/cache@v2
        id: cache_vcpkg
        with:
          path: ${{ github.workspace }}/vcpkg
          key:  ${{ matrix.config.os }}-vcpkg-${{ hashFiles('external/vcpkg_x64-windows-static_response_file.txt') }}

      - uses: actions/cache@v2
        id: ${{ matrix.config.os }}-cache_pip
        if: startsWith( ${{ matrix.config.os }}, 'windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ matrix.config.os }}-pip-x64-${{ hashFiles('external/pip_requirements.txt') }}

      - name: Install vcpkg packages
        if: startsWith(matrix.config.os, 'windows') && steps.cache_vcpkg.outputs.cache-hit != 'true'
        run: |
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat -disableMetrics
          ${{ github.workspace }}/vcpkg/vcpkg install @external/vcpkg_x64-windows-static_response_file.txt
          # cmd "${{ matrix.config.environment_script }}"

      - name: Setup python and install pip packages
        if: steps.${{ matrix.config.os }}-cache_pip.outputs.cache-hit != 'true'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python_version }}
          architecture: x64
      - run: |
          python -m pip install --upgrade pip
          pip install -r external/pip_requirements.txt

      - name: Alter the path to avoid using rtool's tar before cache posting
        if: contains( ${{ matrix.config.os }}, 'windows')
        run: echo "::add-path::C:/Program Files/Git/usr/bin"

      - name: Configure
        shell: bash
        run: |
          mkdir build
          cmake \
            -S . \
            -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -G "${{ matrix.config.generators }}" \
            -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=x64-windows-static \
            -DFIREBASE_INCLUDE_FIRESTORE=OFF

      - name: Build
        shell: bash
        run: cmake --build build --config ${{ matrix.config.build_type }} -j 8

      - name: Print built libraries
        shell: bash
        run: |
          find build -name "*.lib"
